config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :simsettings

  root to: 'pages#index'

  post "/simulate", to: 'pages#simulate'
  get "/simulate/result", to: 'pages#simulate_result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/simsetting.rb
class Simsetting < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # タンク容量、給油するときのメータ位置、燃費
  @@params_temp_vehicle = {fuel_capa: 0, fuel_per1km: 0 ,fuel_threshold: 0}
  # 平日の走行距離、休日の走行距離
  @@params_temp_distance = {dist_univ: 0, dist_holiday: 0}
  # 休日にお出かけする確率（:probability属性に格納予定）
  @@params_temp_probability = 0

  def index
    @simsetting = Simsetting.new
  end

  def simulate

    case params[:simsetting][:fuel_threshold]
    when "半分以上" then
      @@params_temp_vehicle[:fuel_threshold] = 0.6
    when "半分切ったら" then
      @@params_temp_vehicle[:fuel_threshold] = 0.4
    when "少なくなったら" then
      @@params_temp_vehicle[:fuel_threshold] = 0.3
    else
      @@params_temp_vehicle[:fuel_threshold] = 0.1
    end

    case params[:simsetting][:probability]
    when "ほぼほぼ" then
      @@params_temp_probability = 0.8
    when "半々" then
      @@params_temp_probability = 0.5
    when "気が向いたら" then
      @@params_temp_probability = 0.3
    else
      @@params_temp_probability = 0.1
    end


    @@params_temp_vehicle = {fuel_capa: params[:simsetting][:fuel_capa], 
                            fuel_per1km: params[:simsetting][:fuel_per1km]}
    
    @@params_temp_distance = {dist_univ: params[:simsetting][:dist_univ],
                              dist_holiday: params[:simsetting][:dist_holiday]}

    @simsetting = Simsetting.new(fuel_capa: params[:simsetting][:fuel_capa], 
                                fuel_per1km: params[:simsetting][:fuel_per1km], 
                                fuel_threshold: params[:simsetting][:fuel_threshold],
                                dist_univ: params[:simsetting][:dist_univ],
                                dist_holiday: params[:simsetting][:dist_holiday],
                                probability: params[:simsetting][:probability]
                                )
  end

  def simulate_result
    simulate_time        = (1..365).to_a
    normal_random        = RandomBell.new
    distance_dist_normal = @@params_temp_distance[:dist_univ].to_f
    distance_dist_holi   = RandomBell.new(mu: @@params_temp_distance[:dist_holiday].to_f, sigma: (@@params_temp_distance[:dist_holiday].to_f)/2)
    fuel_tank            = 0
    fuel_capa            = @@params_temp_vehicle[:fuel_capa].to_f
    fuel_per1km          = @@params_temp_vehicle[:fuel_per1km].to_f
    fuel_threshold       = fuel_tank * @@params_temp_vehicle[:fuel_threshold].to_f
    fueling_litter       = 0 # 給油量
    total_amountOfrefuel = 0 # 総給油量
    refueling_times      = 0 # 給油回数
    running_distance     = 0 # お出かけ距離
    total_running        = 0 # 総距離
    total_cost           = 0 # 総コスト


    gas_price_array = [ 140.0, 142.0, 144.0, 146.0, 148.0 ]

    simulate_time.each do |i|

      # - - - - 値段設定 - - - - - - - 
      if i == 0
        gas_price = gas_price_array[Random.rand(5)]
      else
        if Random.rand(100)/100 < 0.2
          gas_price = gas_price_array[Random.rand(5)]
        end
      end

      gas_price += normal_random.rand
      # - - - - - - - -  - - - - - - -

      # - - 車両のメータチェック - - - -
      if fuel_tank < fuel_threshold
        fueling_litter = fuel_capa - fuel_tank
        total_amountOfrefuel += fueling_litter
        total_cost += gas_price * fueling_litter
        fuel_tank = fuel_capa
        refueling_times += 1
      end
      # - - - - - - - - - - - - - - - 
      
      # iが6,7ならば，土曜日, 日曜日であると仮定
      if  i % 6 == 0 || i % 7 == 0
        if Random.rand(100)/100 < @@params_temp_probability
          # お出かけの距離
          running_distance = distance_dist_holi.rand
          # 距離が正になるよう調整
          while running_distance <= 0
              running_distance = distance_dist_holi.rand
          end

        total_running += 2 * running_distance
        fuel_tank -= (1.0/fuel_per1km) * 2 * running_distance
        end
      else # 平日
        total_running += distance_dist_normal
        fuel_tank -= (1.0/fuel_per1km) * distance_dist_normal
      end
    end
    @totalCost = total_cost
    @totalRunning = total_running
    @refuelingTimes = refueling_times
    @totalAmountRefuel = total_amountOfrefuel
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ガソリン給油シミュレーション</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container">
    <div class="header-wrapper">
        <h1>ガソリン給油シミュレーション</h1>
    </div>

    <div class="container">
        <h2 align="center" >車両とガソリン価格の情報を入力してください</h2>
        <div class="form-wrapper">
                <%= form_for @simsetting, url: simulate_path do |f| %>
                    <div class="row">
                        <div class="column">
                            <div class="form-group">
                                <%= f.label :fuel_capa, "タンクの容量(L)："%>
                                <%= f.number_field :fuel_capa, class: "form-control", required: true %>
                                <%= f.label :fuel_per1km, "燃費(km/L)：" %>
                                <%= f.number_field :fuel_per1km, step:0.1, class: "form-control", required: true %>
                                <%= f.label :fuel_threshold, "メータがどれくらいで給油しますか？" %>
                                <%= f.select :fuel_threshold, [["半分以上", "半分以上"],["半分切ったら", "半分切ったら"],["少なくなったら", "少なくなったら"],["ランプがついたら", "ランプがついたら"]], {}, class: "form-control dropdown-toggle" %>
                            </div>
                        </div>
                        <div class="column">
                            <div class="form-group">
                                <%= f.label :dist_univ, "平日の平均的な走行距離（km）：" %>
                                <%= f.number_field :dist_univ, step:0.1, class: "form-control", required: true %>
                            
                                <%= f.label :dist_holiday, "休日の平均的な走行距離（km）：" %>
                                <%= f.number_field :dist_holiday, step:0.1, class: "form-control", required: true %>
                            
                                <%= f.label :probability, "休日にお出かけする頻度：" %>
                                <%= f.select :probability, [["ほぼほぼ", "ほぼほぼ"],["半々", "半々"],["気が向いたら", "気が向いたら"],["全然出かけない", "全然出かけない"]], {}, class: "form-control"%>                            
                            </div>
                        </div>
                    </div>
                    <div class="btn-wrapper">
                        <%= f.submit "入力内容確認", class: "btn btn-outline-primary btn-block"%>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/pages/set_gasstand.html.erb
<div class="container">
    <div class="header-wrapper">
        <h1>ガソリン給油シミュレーション</h1>
    </div>

    <div class="bike-wrapper">
        <h2>バイクの情報</h2>
        <p>タンクの容量：<%= @bike.fuel_capa %>
        <p>燃費：<%= @bike.fuel_per1km %>
    </div>


    <div class="gasstand-wrapper">
        <h2>ガソリンスタンドの情報を入力してください</h2>
        <div class="form-wrapper">
            <%= bootstrap_form_for @gasstand, url: simulate_path do |f| %>
                最安値：
                <%= f.number_field :gas_cheap %>
                少し安め：
                <%= f.number_field :gas_littlecheap %>
                普通：
                <%= f.number_field :gas_normal %>
                少し高め：
                <%= f.number_field :gas_littleexpensive %>
                最高値：
                <%= f.number_field :gas_expensive %>
                <%= f.submit "入力完了" %>
            <% end %>
        </div>
    </div>
</div>

app/views/pages/simulate.html.erb
<div class="container">
    <div class="header-wrapper">
        <h1>ガソリン給油シミュレーション</h1>
    </div>
    <div class="vehicle-wrapper">
        <h2>車両の情報</h2>
        <table class="table table-striped table-condensed table-bordered">
            <thead>
                <tr>
                    <th > 項目 </th>
                    <th > 値 </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th >タンクの容量</th>
                    <td ><%= @simsetting.fuel_capa %></td>
                </tr>
                <tr>
                    <th >燃費</th>
                    <td ><%= @simsetting.fuel_per1km %></td>
                </tr>
                <tr>
                    <th >メータがどれくらいで給油しますか？</th>
                    <td ><%= @simsetting.fuel_threshold %></td>
                </tr>
            </tbody>
        </table>
    </div>


    <div class="userinfo-wrapper">
        <h2>乗り方の情報</h2>
        <table class="table table-striped table-condensed table-bordered">
            <thead>
                <tr>
                    <th > 項目 </th>
                    <th > 値 </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th >平日の平均的な走行距離</th>
                    <td ><%= @simsetting.dist_univ %> km</td>
                </tr>
                <tr>
                    <th >休日の平均的な走行距離</th>
                    <td ><%= @simsetting.dist_holiday %> km</td>
                </tr>
                <tr>
                    <th >休日にお出かけする頻度</th>
                    <td ><%= @simsetting.probability %></td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class=btn-wrapper2>
        <%= button_to "シミュレーション開始", {controller: 'pages', action: 'simulate_result'}, {method: :get, class: "btn btn-outline-primary btn-block"} %>
    </div>
</div>

app/views/pages/simulate_result.html.erb
<div class="container">
    <div class="header-wrapper">
        <h1>ガソリン給油シミュレーション</h1>
    </div>
    <div class="result-wrapper">
    <h2 class="center-align">シミュレーション結果</h1>
    <table class="table table-striped table-condensed table-bordered">
        <thead>
            <tr>
                <th > 項目 </th>
                <th > 値 </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th >トータルコスト</th>
                <td ><%= @totalCost.to_i %> 円</td>
            </tr>
            <tr>
                <th >総走行距離</th>
                <td ><%= @totalRunning.to_i %> km </td>
            </tr>
            <tr>
                <th >総給油回数</th>
                <td ><%= @refuelingTimes.to_i %> 回</td>
            </tr>
            <tr>
                <th >総給油量</th>
                <td ><%= @totalAmountRefuel.to_i %> L</td>
            </tr>
        </tbody>
    </table>
    </div>

    <div class=btn-wrapper2>
        <%= link_to "Topに戻る", root_url, class: "btn btn-outline-primary btn-block" %>
    </div>
</div>